services:
  postgres:
    image: postgres:17
    container_name: article-postgres

    environment:
      POSTGRES_DB: article_db
      POSTGRES_USER: article_user
      POSTGRES_PASSWORD: article_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: article-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: